---

- name: Firewall for Ubuntu and CentOS
  hosts: all
  become: true
  tasks:
    - name: Install ufw
      ansible.builtin.apt:
        name: ufw
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install firewalld
      ansible.builtin.yum:
        name: firewalld
        state: present
      when: ansible_distribution == "CentOS"

    - name: Enable ufw
      ansible.builtin.ufw:
        state: enabled
      when: ansible_distribution == "Ubuntu"

    - name: Start and enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Add and enable ports in ufw
      ansible.builtin.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 22
        - 80
        - 443
      when: ansible_distribution == "Ubuntu"

    - name: Add and enable ports in firewalld
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 22/tcp
        - 80/tcp
        - 443/tcp
      when: ansible_distribution == "CentOS"
